### ISSUE TITLE
Add OSTB Series 1 strings to Google Sheet

### ISSUE THREAD

**Issue by mattodd** [OpenSourceTB/OSTB-Compounds#1]
Hi @jessicabaiget - here's an Issue, as an alternative to email! Since this relates to compound numbering I'm creating this here.

We need a way of visualising all the Series 1 compounds that are shown on the wiki (http://openwetware.org/wiki/OpenSourceTB:OSTB_Series_1).

There has been a lot of discussion over in the OSM project on how to manage and visualise the molecules we make. It turns out that if we have a Google sheet with all the compounds listed as their strings then we can easily view all the molecules with some free software. So I created a sheet here:

https://docs.google.com/spreadsheets/d/1VwAvTA0VfRVBMZ9WqEMPaG3YF7-SqBAgjS95NkXJkaE/edit?usp=sharing

and have shortened the link to http://bit.ly/1J2cqw7 for convenience.

So: Can you please populate this sheet with all our Series 1 compounds?

Should be self-explanatory. Once this is done we can easily view all the structures - see how well this works for the OSM project, where this is the current output:

http://www.cheminfo.org/Chemistry/Parsing%20data/Tab_delimited_Parallel_Coordinates.html?tsvURL=http%3A%2F%2Fgoogledocs.cheminfo.org%2Fspreadsheets%2Fd%2F1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc%2Fexport%3Fformat%3Dtsv

Once all the Series 1 compounds are in there, we can close this issue.

**Comment by jessicabaiget** [comment]
Hi @mattodd 
The table is completed. However, the activity column has been divided in two, one for the IC50 and other for the MIC . If you are happy with that, I can close this issue

Cheers
Jessica

**Comment by mattodd** [comment]
Good point - we need to be more precise with our terms. As I understand it MIC and IC50 can be usedinterchangably if we're not careful. Can you ask the guys at GSK whether the values they obtained are MIC50 or MIC90 - what's typical? Am I right in thinking that the other values described as IC50 were from the Uni Sydney team? If so I will seek clarification from them.

Keep the columns separate for now, yes!

**Comment by jessicabaiget** [comment]
Hello @mattodd 
I want to assign OSTBS number to series 2 compounds, so I can write them in the schemes. According last discussion, we should also include intermediates, therefore compound OSTBS27 should be the first intermediate JBG28-1-1 (https://au-mynotebook.labarchives.com/share/Jessica%2520Baiget%2520Gonzalez/ODUuOHw2NTUvNjYvVHJlZU5vZGUvMjE3NzMwMzA3OHwyMTcuOA==
) (see scheme http://openwetware.org/wiki/OpenSourceTB:OSTB_Series_2#Synthetic_Chemistry).

 Is that ok? I have no biological data for almost all the intermediates, so should I include them for the OSTBS numbering in any case?
Thanks

**Comment by mattodd** [comment]
Yes, the synthetic intermediates should receive OSTB numbers even if they
are not biologically evaluated, but you don't have to make them have
numbers in order - they just need numbers. i.e. if you want to number them
in order, fine, but it's not necessary, provided everything structure has a
unique OSTB number.

On 22 May 2015 at 04:45, jessicabaiget notifications@github.com wrote:

>  Hello @mattodd https://github.com/mattodd
> I want to assign OSTBS number to series 2 compounds, so I can write them
> in the schemes. According last discussion, we should also include
> intermediates, therefore compound OSTBS27 should be the first intermediate
> JBG28-1-1 (
> https://au-mynotebook.labarchives.com/share/Jessica%2520Baiget%2520Gonzalez/ODUuOHw2NTUvNjYvVHJlZU5vZGUvMjE3NzMwMzA3OHwyMTcuOA==
> ) (see scheme
> http://openwetware.org/wiki/OpenSourceTB:OSTB_Series_2#Synthetic_Chemistry
> ).
> 
> Is that ok? I have no biological data for almost all the intermediates, so
> should I include them for the OSTBS numbering in any case?
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenSourceTB/OSTB-Compounds/issues/1#issuecomment-104616031
> .

## 

MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by mattodd** [comment]
Hi Jessica - can I close this Issue? In other words, did you finish adding all the synthetic intermediates for Series 1 to the Google Sheet? If not, I'll keep this Issue open.

**Comment by jessicabaiget** [comment]
Hi @mattodd 
I added all final compounds of series 1 and almost all compounds series 2 and series 2 intermediates.
I haven't added series 1 intermediates because few of us worked in this series and to add just my intermediates was a bit confusing, but if you consider it is better I will add them as soon I can.
Let me know
Cheers

Jessica

**Comment by mattodd** [comment]
Yes, please just complete the addition of any compounds you have made. No need to worry about the compounds made by others for now. Thanks. I'm closing this Issue.
