### ISSUE TITLE
Adding png and chemdraw files here

### ISSUE THREAD

**Issue by mattodd** [OpenSourceTB/OSTB-Compounds#2]
Hi @jessicabaiget - we can use the parent page to this one (https://github.com/OpenSourceTB/OSTB-Compounds) as a place to store image files for all the molecules. To do this you need access to the shared dropbox folder OSTB -> OSTB-Compounds. Do you have this folder in your Dropbox? You should be able to see a folder there called "Series 1" containing .cdxml and .png files for OSTBS compounds up to 26. Can you see that?

**Comment by jessicabaiget** [comment]
Hi @mattodd 
yes, I have the folder and I can see the .png and .cdxml files

**Comment by mattodd** [comment]
OK, perfect! So for any structure that you name with an OSTB code, please add the .png and .cdxml files to that folder, using the examples already there to define the drawing settings. This means we have a complete set of chemdraw files for all the molecules in OSTB should they be needed. I'm pretty sure that's useful. Going to close this issue now.
